Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-06, with the labels that each got.

#22 [NOD-928] fix: refactoring on debt position handling
  .github/workflows/04h_deploy_with_github_runner.yml
  README.md
  integration-test/system-test/src/requests/rpt/ok_nostamp.js
  openapi-client/gpd/openapi.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/wispconverter/config/client/GpdClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RTCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RptCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/CartMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionUpdateMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/ReEventMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/ReceiptDto.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/EntityStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/CommonFieldsDTO.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/PaymentNoticeContentDTO.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/PaymentPositionExistence.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/RPTContentDTO.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/SessionDataDTO.java
  src/main/resources/application.properties
  src/main/resources/xsd/PagInf_RPT_RT_6_2_0.xsd
Labels: patch, size/large

#24 fix: Made changes on flow due to wrong Receipt handling
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/CommonFieldsDTO.java
Labels: patch, size/small

#25 [PAGOPA-1832] fix: Check station related to payment notice during existing payment position analysis
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/EntityStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/resources/application.properties
Labels: patch

#26 [PAGOPA-1834] feat: Enhancing Registro Eventi's event tracing
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/config/client/CheckoutClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/DecouplerCachingClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/GpdClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/IuvGeneratorClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RedirectController.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/ReEventEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/CategoriaEventoEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ComponentEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/EsitoEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/EventCategoryEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/EventSubcategoryEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/OutcomeEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RTCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RptCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/CallTypeEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/CategoriaEventoEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/ComponenteEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/EntityStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/EsitoEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/ReEventDto.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/SottoTipoEventoEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/CommonFieldsDTO.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/SessionDataDTO.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/AbstractAppClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/apiconfigcache/ApiConfigCacheClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/checkout/CheckoutClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/decouplercaching/DecouplerCachingClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/gpd/GpdClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/iuvgenerator/IuvGeneratorClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/filter/AbstractAppServerLoggingFilter.java
  src/main/java/it/gov/pagopa/wispconverter/util/filter/AppServerLoggingFilterFilter.java
  src/main/java/it/gov/pagopa/wispconverter/util/filter/ReFilter.java
  src/main/java/it/gov/pagopa/wispconverter/util/interceptor/AbstractAppServerLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/interceptor/ReInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/openapi/OpenAPIDescriptionCustomizer.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: patch, size/large

#27 [PAGOPA-1837] Refactoring JUnit tests
  openapi/openapi.json
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/AbstractAppClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/interceptor/AbstractAppServerLoggingInterceptor.java
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/utility/BaseTest.java
  src/test/java/it/gov/pagopa/wispconverter/utility/LoggingTest.java
  src/test/java/it/gov/pagopa/wispconverter/utility/XmlUtilTest.java
  src/test/java/it/gov/pagopa/wispconverter/utility/ZipUtilTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/ConstantsTestHelper.java
  src/test/java/it/gov/pagopa/wispconverter/utils/TestUtils.java
  src/test/resources/requests/rptBollo.xml
  src/test/resources/requests/rptCart.xml
  src/test/resources/requests/rptNullIban.xml
Labels: bug, patch, size/large

#28 chore: [PAGOPA-1852] Fake endpoint for APIM implementations
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/ReceiptTimerRequest.java
Labels: patch, size/small

#29 [PAGOPA-1852] feat: Add Create and Delete Timer API with Consumer
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptTimerController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/ReceiptTimerRequest.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/ReceiptDto.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/PaymentTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/SBConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/LogUtils.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/PaymentTimeoutConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ReceiptTimerServiceTest.java
Labels: patch, size/large

#33 fix: resolved various errors on broken JUnit tests
  openapi/openapi.json
  src/main/java/it/gov/pagopa/wispconverter/service/ServiceBusService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/TestUtils.java
  src/test/resources/application-test.properties
  src/test/resources/requests/paSendRTV2.xml
  src/test/resources/requests/paaInviaRT.xml
Labels: patch, size/large

#34 feat: Update servicebus connection string
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/wispconverter/Application.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ServiceBusService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/PaymentTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/resources/application.properties
Labels: patch, size/small

#35 fix: changed checks on station
  openapi/openapi.json
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
Labels: patch, size/small

#36 fix: changed checks for segregation code on station
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
Labels: patch, size/small

#37 fix: Some minor refactoring after first tests in DEV
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/CartMapper.java
Labels: patch
