Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-12, with the labels that each got.

#186 [PAGOPA-2389] feat: Force idempotency-key when receipt-ok
  src/main/java/it/gov/pagopa/wispconverter/service/IdempotencyService.java
Labels: patch, size/small

#184 [PAGOPA-2389] feat: Add new PAYING status
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptTimerController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RedirectController.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ReceiptStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RtReceiptCosmosService.java
Labels: patch, size/small

#182 fix: improvements on RE events info
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/AbstractAppClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/apiconfigcache/ApiConfigCacheClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/checkout/CheckoutClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/decouplercaching/DecouplerCachingClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/gpd/GpdClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/iuvgenerator/IuvGeneratorClientLoggingInterceptor.java
Labels: patch, size/small

#185 feat: increasing consistency level of cosmos db client PAGOPA-2414
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  performance-test/src/test-types/spike.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/config/CosmosDBConfig.java
  src/main/resources/application.properties
Labels: bug, enhancement, patch, size/small

#187 feat: update config cache host url and path PAGOPA-2442 (BLOCKED)
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi-client/apiconfig-cache/openapi_cache.json
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/resources/application.properties
Labels: enhancement, patch, size/small
