Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-10, with the labels that each got.

#127 [PAGOPA-2208] fix: segregation code changed from 48 to 51
  src/main/resources/application.properties
Labels: ignore-for-release, size/small, minor

#105 [PAGOPA-2113] feat: Add Recovery Cron
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/wispconverter/config/SecondaryCosmosConfig.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/repository/RTRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/ReEventRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/SessionIdEntity.java
  src/main/java/it/gov/pagopa/wispconverter/scheduler/RecoveryScheduler.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/RTRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/ReEventRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ConfigurationControllerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/StaticPagesTest.java
  src/test/java/it/gov/pagopa/wispconverter/repository/CacheRepositoryTest.java
  src/test/java/it/gov/pagopa/wispconverter/scheduler/RecoverySchedulerTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConfigurationServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/RecoveryServiceTest.java
  src/test/resources/application-test.properties
Labels: patch, size/large

#129 [PAGOPA-2113] chore: Disable cron
  helm/values-prod.yaml
Labels: ignore-for-release, size/small

#128 [PAGOPA-2226] fix: resolved wrongly formatted date
  src/main/java/it/gov/pagopa/wispconverter/util/XmlUtil.java
Labels: patch, size/small

#133 [PAGOPA-2229] fix: Update rt `SENDING` status
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/test/java/it/gov/pagopa/wispconverter/utility/XmlUtilTest.java
Labels: patch, size/small

#132 [PAGOPA-2216] feat: refactored receipt recovery endpoint
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptReportResponse.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptRequest.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/ReEventRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ServiceBusService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/ReceiptContentDTO.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/ECommerceHangTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/PaymentTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RPTTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/JaxbElementUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/RTNamespaceMapper.java
  src/main/resources/application.properties
Labels: patch, size/large

#139 [PAGOPA-2248] Fix riferimentoDataRichiesta
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
Labels: patch

#136 [PAGOPA-2238] fix: refactored max retries for paaInviaRT send
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
Labels: patch, size/small

#135 [PAGOPA-2235] fix(RPT-timer): Exception handling
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTTimerService.java
Labels: patch, size/small, on hold

#142 chore: Recovery by partition
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptByPartitionRequest.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
Labels: ignore-for-release

#143 chore: Add station to receipt
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
Labels: ignore-for-release

#134 chore: updat EC error deadLetter logic Pagopa 2227
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/ReceiptDeadLetterRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/ReceiptDeadLetterEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ReceiptStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ConfigurationControllerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/StaticPagesTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConfigurationServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/RPTTimerServiceTest.java
Labels: enhancement, patch, size/large

#131 [PAGOPA-2113] ci: Add wisp converter cron replica
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/scheduler/RecoveryScheduler.java
Labels: patch, size/small

#146 feat: Release v0.4.6
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptByPartitionRequest.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptReportResponse.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptRequest.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/ReceiptDeadLetterRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/ReceiptDeadLetterEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ReceiptStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/ReEventRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ServiceBusService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/ReceiptContentDTO.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/ECommerceHangTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/PaymentTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RPTTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/JaxbElementUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/RTNamespaceMapper.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ConfigurationControllerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/StaticPagesTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConfigurationServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/RPTTimerServiceTest.java
Labels: patch, size/large

#148 [PAGOPA-2249] fix: ECommerceHangTimer with sessionId
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/model/ReceiptTimerRequest.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/ECommerceHangTimeoutMessage.java
  src/test/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ReceiptTimerServiceTest.java
Labels: bug, patch, size/small

#149 fix: [PAGOPA-2283] Remove recovered receipt if in dead-letter
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerServiceTest.java
Labels: patch, size/small

#151 fix(cache-mapping): Fix not-idempotent mapping `iuv2sessionId` [PAGOPA-2284]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/ReceiptDto.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/ECommerceHangTimeoutConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/resources/requests/paSendRTV2.xml
Labels: patch, size/small

#152 chore: [PAGOPA-2286] Added recovery by sessionId
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptBySessionIdRequest.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/IdempotencyKeyRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/ReEventRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
Labels: patch, size/small

#156 [PAGOPA-2261] feat: Enable CRON
  helm/values-prod.yaml
  src/main/java/it/gov/pagopa/wispconverter/secondary/RTRepositorySecondary.java
Labels: patch, size/small

#154 feat(report-gen): [PAGOPA-2212] introducing automatic report generation for statistics publication
  .github/workflows/07_report_generation.yml
  .github/workflows/07b_report_send.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
  scripts/report-generation/README.md
  scripts/report-generation/config.json
  scripts/report-generation/datastructs/configuration.py
  scripts/report-generation/datastructs/dtos.py
  scripts/report-generation/datastructs/entities.py
  scripts/report-generation/datastructs/report.py
  scripts/report-generation/logic/clients.py
  scripts/report-generation/logic/extraction.py
  scripts/report-generation/logic/slack_webhook.py
  scripts/report-generation/requirements.txt
  scripts/report-generation/run_extraction.py
  scripts/report-generation/run_send.py
  scripts/report-generation/utility/constants.py
  scripts/report-generation/utility/utility.py
Labels: ignore-for-release, size/large

#159 fix: nav2iuv with multiple '_' PAGOPA-2316
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/test/java/it/gov/pagopa/wispconverter/service/DecouplerServiceTest.java
Labels: bug, patch, size/small

#160 BUG: [PAGOPA-2300] delta exp time
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptTimerController.java
  src/main/resources/application.properties
Labels: bug, patch, size/small

#157 ci: Disable cron autoscaling
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#161 feat: Included detailed info in reports about KOs on payment flows
  .github/workflows/07_report_generation.yml
  scripts/report-generation/datastructs/entities.py
  scripts/report-generation/datastructs/report.py
  scripts/report-generation/logic/clients.py
  scripts/report-generation/logic/extraction.py
  scripts/report-generation/run_actualization.py
  scripts/report-generation/run_massive_extraction.py
  scripts/report-generation/utility/constants.py
  scripts/report-generation/utility/utility.py
Labels: patch

#162 feat (receipts) [PAGOPA-2301]: Made NAV-to-IUV mapping more resilient
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/repository/NavToIuvMappingRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/NavToIuvMappingEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ConfigurationControllerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/StaticPagesTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConfigurationServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/DecouplerServiceTest.java
Labels: patch
