Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-03, with the labels that each got.

#1 feat: NOD-784 upgrade version
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/wispconverter/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/wispconverter/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/RedisConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/RequestFilter.java
  src/main/java/it/gov/pagopa/wispconverter/config/ResponseValidator.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ServiceController.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppException.java
  src/main/java/it/gov/pagopa/wispconverter/exception/ErrorHandler.java
  src/main/java/it/gov/pagopa/wispconverter/model/ProblemJson.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/resources/application.properties
Labels: patch

#2 [NOD-781] feat: merged different methods in new structure
  .DS_Store
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/client/DecouplerCachingClient.java
  src/main/java/it/gov/pagopa/wispconverter/client/GPDClient.java
  src/main/java/it/gov/pagopa/wispconverter/config/CosmosDBConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/RedisConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/DecouplerCachingFeignConfig.java
  src/main/java/it/gov/pagopa/wispconverter/exception/conversion/ConversionException.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/MultiplePaymentPosition.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/PaymentOption.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/PaymentOptionMetadata.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/PaymentPosition.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/Stamp.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/Transfer.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/TransferMetadata.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/Type.java
  src/main/java/it/gov/pagopa/wispconverter/model/unmarshall/RPTContent.java
  src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
  src/main/java/it/gov/pagopa/wispconverter/service/CacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/UnmarshallerService.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/resources/application.properties
Labels: ignore-for-release

#3 feat: main branch alignment for next parallel task working
  .DS_Store
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  scripts/update-specs.sh
  src/main/java/it/gov/pagopa/wispconverter/Application.java
  src/main/java/it/gov/pagopa/wispconverter/client/DecouplerCachingClient.java
  src/main/java/it/gov/pagopa/wispconverter/client/GPDClient.java
  src/main/java/it/gov/pagopa/wispconverter/client/IUVGeneratorClient.java
  src/main/java/it/gov/pagopa/wispconverter/config/CosmosDBConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/wispconverter/config/RedisConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/UnmarshallerConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/AuthFeignConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/DecouplerCachingFeignConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/GPDFeignConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/IUVGeneratorFeignConfig.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RedirectController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ServiceController.java
  src/main/java/it/gov/pagopa/wispconverter/entity/Primitive.java
  src/main/java/it/gov/pagopa/wispconverter/entity/RPTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppError.java
  src/main/java/it/gov/pagopa/wispconverter/exception/conversion/ConversionException.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/MultiplePaymentPosition.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/PaymentOption.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/PaymentOptionMetadata.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/PaymentPosition.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/Stamp.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/Transfer.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/TransferMetadata.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/gpd/Type.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/iuvgenerator/IUVGeneratorRequest.java
  src/main/java/it/gov/pagopa/wispconverter/model/client/iuvgenerator/IUVGeneratorResponse.java
  src/main/java/it/gov/pagopa/wispconverter/model/converter/ConversionResult.java
  src/main/java/it/gov/pagopa/wispconverter/model/unmarshall/RPTContent.java
  src/main/java/it/gov/pagopa/wispconverter/model/unmarshall/RPTRequest.java
  src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/RPTRequestRepository.java
  src/main/java/it/gov/pagopa/wispconverter/service/CacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/NAVGeneratorService.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/FileReader.java
  src/main/java/it/gov/pagopa/wispconverter/util/JaxbElementUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/ZipUtil.java
  src/main/resources/application.properties
  src/main/resources/static/error.html
  src/main/resources/wsdl/NodoPerPa.wsdl
  src/main/resources/xsd/PagInf_RPT_RT_6_2_0.xsd
  src/main/resources/xsd/envelope.xsd
  src/main/resources/xsd/sac-common-types-1.0.xsd
  src/test/resources/application.properties
Labels: ignore-for-release, size/large

#4 feat: Unified error handling
  .gitattributes
  src/main/java/it/gov/pagopa/wispconverter/config/WebMvcConfig.java
  src/main/java/it/gov/pagopa/wispconverter/controller/HomeController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/RedirectController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/advice/ErrorHandler.java
  src/main/java/it/gov/pagopa/wispconverter/controller/advice/model/ApiErrorResponse.java
  src/main/java/it/gov/pagopa/wispconverter/controller/advice/model/ProblemJsonResponse.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppClientException.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppError.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppException.java
  src/main/java/it/gov/pagopa/wispconverter/service/CacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/NAVGeneratorService.java
  src/main/java/it/gov/pagopa/wispconverter/util/AppErrorUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/JaxbElementUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/aspect/LoggingAspect.java
  src/main/java/it/gov/pagopa/wispconverter/util/aspect/ResponseValidator.java
  src/main/resources/messages/messages_en.properties
  src/main/resources/messages/messages_it.properties
Labels: patch, size/large
