Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-07, with the labels that each got.

#39 fix: Several minor fixes after integration tests
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptTimerController.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ClientEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/MDCUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/AbstractAppClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/checkout/CheckoutClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/decouplercaching/DecouplerCachingClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/gpd/GpdClientLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/client/iuvgenerator/IuvGeneratorClientLoggingInterceptor.java
  src/test/java/it/gov/pagopa/wispconverter/service/ReceiptTimerServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/utility/LoggingTest.java
Labels: patch, size/small

#38 [PAGOPA-1889] feat: OpenAPI groups
  infra/04_apim_api.tf
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/config/OpenApiConfig.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
Labels: patch, size/small

#40 fix: send receipt logging
  helm/Chart.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptTimerController.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ClientEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RptCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReUtil.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
Labels: patch, size/small

#41 [PAGOPA-1903] fix: set handling of forwarder endpoints in paaInviaRT send
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
Labels: patch

#43 [PAGOPA-1905] fix: changes on flow and on RE
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ServiceBusService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/MDCUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReUtil.java
  src/main/resources/application.properties
  src/main/resources/i18n/messages_en.properties
  src/main/resources/i18n/messages_it.properties
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
Labels: patch

#45 [PAGOPA-1919] fix: resolved bug on debtors for non-multibeneficiary cart
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
Labels: patch

#46 [PAGOPA-1921] fix: resolved bug on paaInviaRT duplicated send
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/TestUtils.java
  src/test/resources/requests/paSendRTV2.xml
  src/test/resources/requests/rpt.xml
Labels: patch, size/small

#47 fix: [PAGOPA-1923] Try to fix redirect url
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
Labels: patch, size/small

#44 [PAGOPA-1920] fix: Update RTConsumer receiverClient
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppException.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/PaymentTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/SBConsumer.java
  src/main/resources/i18n/messages_en.properties
  src/test/java/it/gov/pagopa/wispconverter/consumer/PaymentTimeoutConsumerTest.java
Labels: patch, size/small

#48 [PAGOPA-1928] fix: add 'Content-Type' header for paaInviaRT request
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
Labels: patch, size/small

#49 fix: refactored `paaInviaRT` request namespaces
  helm/Chart.yaml
  openapi/openapi.json
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/TestUtils.java
Labels: patch, size/small

#50 [PAGOPA-1939] fix: resolved issues found on tests with creditor institution
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/PaymentRequestDomainDTO.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/CommonFieldsDTO.java
  src/main/resources/application.properties
Labels: patch, size/small

#51 [PAGOPA-1940] fix: resolved bug on wrong stamp conversion
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RPTMapper.java
Labels: patch, size/small

#52 [PAGOPA-1942] fix:
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/RedirectController.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
Labels: patch, size/small

#53 [PAGOPA-1941] fix: Relaxed constraint on common creditor institution in non-multibeneficary cart
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/CommonFieldsDTO.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/MDCUtil.java
Labels: patch, size/small

#54 [PAGOPA-1956] fix: resolved bugs caused by regression
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/session/SessionDataDTO.java
Labels: patch

#55 fix: Refactored Java heap due to OOM problem
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
Labels: patch

#56 [PAGOPA-1908] cd: Update helm prod
  helm/values-prod.yaml
Labels: patch, size/small

#57 [PAGOPA-1908] cd: Update values-prod.yaml
  helm/values-prod.yaml
Labels: patch, size/small

#62 [PAGOPA-1962] fix: set debt position 'pull' flag to false
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/DebtPositionMapper.java
Labels: patch

#64 [PAGOPA-1964] fix: resolved bugs after unhappy-case tests
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/Application.java
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/utility/LoggingTest.java
Labels: patch, size/small

#67 PAGOPA-1827 updating collection with last tests
  postman-collection/Dismissione WISP.postman_collection.json
Labels: enhancement, patch, size/large

#66 [PAGOPA-1974] fix: add parachute when the generation of RT is required on non-existing debt position
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
Labels: patch, size/small

#68 [PAGOPA-1974] fix: add parachute when the generation of RT is required on non-existing debt position
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
Labels: patch

#69 fix: resolved wrong merge
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
Labels: patch

#71 [PAGOPA-1967] fix: Update postman collection MBD
  postman-collection/Dismissione WISP.postman_collection.json
Labels: patch, size/small
