Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-09, with the labels that each got.

#84 [PAGOPA-2080] fix: Adjust `id` when find RT
  src/main/java/it/gov/pagopa/wispconverter/service/RtReceiptCosmosService.java
Labels: patch, size/small

#85 [PAGOPA-2086] feat: add endpoint for expose static error page
  src/main/java/it/gov/pagopa/wispconverter/controller/StaticPagesController.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/StaticPagesTest.java
Labels: patch, size/small

#86 [PAGOPA-2087] feat: add handling of `save-cart-mapping` keys
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi-client/decoupler-caching/openapi.json
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
Labels: patch

#83 [PAGOPA-2056] wisp converter sviluppo invio rt in caso di abbandono dalla pagina email di e commerce
  .github/workflows/02_check_pr.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi-client/decoupler-caching/openapi.json
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/model/ReceiptTimerRequest.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/ECommerceHangTimeoutMessage.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/ECommerceHangTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/MDCUtil.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/repository/CacheRepositoryTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ReceiptTimerServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/servicebus/ECommerceHangTimeoutConsumerTest.java
  src/test/resources/application-test.properties
Labels: enhancement, patch, size/large

#89 [PAGOPA-2089] feat: Add Recovery API
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptPaymentResponse.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptResponse.java
  src/main/java/it/gov/pagopa/wispconverter/repository/RTRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/ReEventRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/resources/application-test.properties
Labels: patch, size/large

#92 [PAGOPA-2102] fix: resolved wrong time unit on ecommerce-hang-timer
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
Labels: patch

#90 [PAGOPA-2099] fix: refactored PAA_RT_DUPLICATA error code handling
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
Labels: patch, size/small

#87 [PAGOPA-1991] feat: definition of integration test for WISP Dismantling
  .github/workflows/05_integration_test.yml
  .gitignore
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
  README.md
  api-test/cucumber/README.md
  api-test/cucumber/run_integration_test.sh
  api-test/cucumber/src/README.md
  api-test/cucumber/src/config/.env.dev
  api-test/cucumber/src/config/.env.local
  api-test/cucumber/src/config/.env.prod
  api-test/cucumber/src/config/.env.uat
  api-test/cucumber/src/features/example.feature
  api-test/cucumber/src/package.json
  api-test/cucumber/src/step_definitions/support/common.js
  api-test/cucumber/src/step_definitions/support/steps.js
  api-test/system-test/README.md
  api-test/system-test/run.sh
  api-test/system-test/src/.nvmrc
  api-test/system-test/src/config/.env.dev
  api-test/system-test/src/lib/client.js
  api-test/system-test/src/lib/util.js
  api-test/system-test/src/package-lock.json
  api-test/system-test/src/package.json
  api-test/system-test/src/requests/rpt/ko_withstamp.js
  api-test/system-test/src/requests/rpt/ok_nostamp.js
  api-test/system-test/src/start.js
  integration-test/Dockerfile
  integration-test/README.MD
  integration-test/behave.ini
  integration-test/config/commondata.json
  integration-test/config/config.json
  integration-test/environment.py
  integration-test/features/common.feature
  integration-test/features/nodoInviaCarrelloRPT/common.feature
  integration-test/features/nodoInviaCarrelloRPT/nodoInviaCarrelloRPT_existingPaymentPosition.feature
  integration-test/features/nodoInviaCarrelloRPT/nodoInviaCarrelloRPT_multibeneficiary.feature
  integration-test/features/nodoInviaCarrelloRPT/nodoInviaCarrelloRPT_noStamp.feature
  integration-test/features/nodoInviaCarrelloRPT/nodoInviaCarrelloRPT_withStamp.feature
  integration-test/features/nodoInviaRPT/common.feature
  integration-test/features/nodoInviaRPT/nodoInviaRPT_existingPaymentPosition.feature
  integration-test/features/nodoInviaRPT/nodoInviaRPT_noStamp.feature
  integration-test/features/nodoInviaRPT/nodoInviaRPT_withStamp.feature
  integration-test/requirements.txt
  integration-test/run_test.sh
  integration-test/steps/constants.py
  integration-test/steps/request_generator.py
  integration-test/steps/router.py
  integration-test/steps/steps.py
  integration-test/steps/utility/session.py
  integration-test/steps/utility/utils.py
Labels: patch, size/large

#93 PAGOPA-2105 adding configuration for ecs and stations
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/controller/ConfigurationController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/ConfigurationResponse.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/ConfigurationRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/ConfigurationEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigurationService.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
Labels: enhancement, patch, size/small

#96 feat: Pagopa 2108 new CI&Stations api configuration
  openapi/openapi.json
  postman-collection/Dismissione WISP.postman_collection.json
  src/main/java/it/gov/pagopa/wispconverter/controller/ConfigurationController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/ConfigurationModel.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/ConfigurationEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigurationService.java
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/PaymentTimeoutConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ConfigurationControllerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTimerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/StaticPagesTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConfigurationServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/MockBeans.java
Labels: enhancement, patch, size/large

#101 [PAGOPA-2117] fix(RTMapper): Fix mapping XSD BigDecimal.ZERO
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
  src/main/java/it/gov/pagopa/wispconverter/util/XmlUtil.java
Labels: patch, size/small

#82 Pagopa 1818 soap wisp performance test
  .devops/performance-test-pipelines.yml
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/main_scanario.js
  performance-test/src/modules/client.js
  performance-test/src/modules/data.js
  performance-test/src/modules/helpers.js
  performance-test/src/modules/papaparse.min.js
  performance-test/src/nodoInviaCarrelloRPT_workflow.js
  performance-test/src/nodoInviaRPT_workflow.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/smoke.json
Labels: enhancement, ignore-for-release, size/large

#98 [PAGOPA-2109] custom client
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/config/client/APIConfigCacheClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/CheckoutClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/DecouplerCachingClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/GpdClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/IuvGeneratorClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/custom/ApiConfigCacheApiClient.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/custom/CheckoutApiClient.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/custom/DecouplerApiClient.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/custom/GpdApiClient.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/custom/IuvGeneratorApiClient.java
  src/main/resources/application.properties
Labels: patch, size/large

#99 bug: [PagoPA-2093] - GPD error 500
  src/main/java/it/gov/pagopa/wispconverter/config/client/GpdClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConverterServiceTest.java
Labels: ignore-for-release, size/small

#102 [PAGOPA-2122] fix: actualization of multibeneficiary paSendRTV2
  .gitignore
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
Labels: patch

#103 chore: refactored log traces for AppInsight tuning
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/ECommerceHangTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/ECommerceHangTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/PaymentTimeoutConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/SBConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/MDCUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReUtil.java
Labels: patch, size/small

#107 [PAGOPA-2132] fix: resolved wrong formattation for RT dates
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/wispconverter/util/XmlUtil.java
  src/test/java/it/gov/pagopa/wispconverter/utility/XmlUtilTest.java
Labels: bug, patch

#108 [PAGOPA-2125] fix: avoid exception throw if is impossible to delete message from ServiceBus
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/repository/CacheRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/InternalStepStatus.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptTimerService.java
Labels: bug, patch

#109 fix traces
  src/main/java/it/gov/pagopa/wispconverter/controller/RPTTimerController.java
Labels: bug, patch, size/small

#110 [PAGOPA-2150] fix: changed wrongly referenced creditor institution in RT header
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
Labels: bug, patch, size/small

#113 PAGOPA-2153 adding check for existence of sessionId in wisp
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/RPTTimerController.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTTimerService.java
  src/test/resources/application-test.properties
Labels: bug, patch, size/small

#111 [PAGOPA-2148] fix junit test
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/ConverterServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/MockBeans.java
  src/test/resources/application-test.properties
Labels: patch, size/small

#114 [PAGOPA-2156] fix: tuning of RPT_TIMEOUT after received feedbacks
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, patch, size/small

#115 [PAGOPA-2160] fix: resolved bug on wrong sessionID extraction
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/RtRetryComosService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
Labels: bug, patch, size/small

#117 [PAGOPA-2170] fix: resolved bug on idempotency key check
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/IdempotencyService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
Labels: patch, size/small

#106 [PAGOPA-2104] feat: Add new recovery by IUV API
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryReceiptPaymentResponse.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/RecoveryTest.java
  src/test/java/it/gov/pagopa/wispconverter/repository/CacheRepositoryTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/RecoveryServiceTest.java
Labels: patch, size/large

#118 [PAGOPA-2113] feat: Enable multi-region cosmos for read replica
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/config/SecondaryCosmosConfig.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/RTRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/secondary/ReEventRepositorySecondary.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/resources/application.properties
Labels: enhancement

#116 [PAGOPA-2158] feat: add sessionId on logged error response
  src/main/java/it/gov/pagopa/wispconverter/util/ErrorUtil.java
Labels: ignore-for-release, size/small

#120 [PAGOPA-2177] feat: introduced proxy handling for communication with creditor institution
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryProxyReceiptRequest.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryProxyReceiptResponse.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/ProxyUtility.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/TestUtils.java
Labels: ignore-for-release

#119 [PAGOPA-2180] fix: correct handling of stamps in RT
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
Labels: ignore-for-release, size/small

#122 Release v0.3.5
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryProxyReceiptRequest.java
  src/main/java/it/gov/pagopa/wispconverter/controller/model/RecoveryProxyReceiptResponse.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/RTMapper.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/CommonUtility.java
  src/main/java/it/gov/pagopa/wispconverter/util/ErrorUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/ProxyUtility.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/TestUtils.java
Labels: patch, size/large

#123 feat: [PAGOPA-2032] sendRTV2 log
  src/main/java/it/gov/pagopa/wispconverter/controller/ReceiptController.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReceiptRequestHandler.java
  src/test/java/it/gov/pagopa/wispconverter/utility/LoggingTest.java
  src/test/java/it/gov/pagopa/wispconverter/utils/ReceiptRequestHandlerTest.java
  src/test/resources/requests/paSendRTV2Request.xml
Labels: patch, size/small

#125 [PAGOPA-2181] fix: included domain ID in idempotency key
  helm/Chart.yaml
  src/main/java/it/gov/pagopa/wispconverter/repository/RTRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/IdempotencyKeyEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/enumz/ReceiptStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConverterService.java
  src/main/java/it/gov/pagopa/wispconverter/service/IdempotencyService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RecoveryService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RtReceiptCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/RecoveryServiceTest.java
Labels: patch

#126 [PAGOPA-2206] fix: replaced NAV with IUV in idempotency key generation
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_redirect.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/service/IdempotencyService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/test/java/it/gov/pagopa/wispconverter/consumer/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/endpoint/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/service/PaaInviaRTSenderServiceTest.java
Labels: patch, size/small
