Repository pagopa/pagopa-wisp-converter, pull requests merged in 2024-05, with the labels that each got.

#19 [NOD-890] fix: Enrichment on RE events for tracing purpose
  helm/Chart.yaml
  helm/values-dev.yaml
  src/main/java/it/gov/pagopa/wispconverter/repository/model/ReEventEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/CheckoutService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DecouplerService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RPTExtractorService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/ReEventDto.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/ReUtil.java
Labels: patch

#20 chore: Migrazione redis multiAZ
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#21 Nod 886 paa invia rt su eh da wisp converter
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/wispconverter/Application.java
  src/main/java/it/gov/pagopa/wispconverter/config/ScheduledJobsConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/APIConfigCacheClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/DecouplerCachingClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/config/client/IuvGeneratorClientConfig.java
  src/main/java/it/gov/pagopa/wispconverter/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/wispconverter/exception/PaaInviaRTException.java
  src/main/java/it/gov/pagopa/wispconverter/repository/ReEventRepository.java
  src/main/java/it/gov/pagopa/wispconverter/repository/model/RTRequestEntity.java
  src/main/java/it/gov/pagopa/wispconverter/service/ConfigCacheService.java
  src/main/java/it/gov/pagopa/wispconverter/service/DebtPositionService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTService.java
  src/main/java/it/gov/pagopa/wispconverter/service/PaaInviaRTServiceBusService.java
  src/main/java/it/gov/pagopa/wispconverter/service/RTCosmosService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReService.java
  src/main/java/it/gov/pagopa/wispconverter/service/ReceiptService.java
  src/main/java/it/gov/pagopa/wispconverter/service/mapper/ReEventMapper.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/EntityStatusEnum.java
  src/main/java/it/gov/pagopa/wispconverter/service/model/re/ReEventDto.java
  src/main/java/it/gov/pagopa/wispconverter/servicebus/RTConsumer.java
  src/main/java/it/gov/pagopa/wispconverter/util/Constants.java
  src/main/java/it/gov/pagopa/wispconverter/util/JaxbElementUtil.java
  src/main/java/it/gov/pagopa/wispconverter/util/interceptor/AbstractAppServerLoggingInterceptor.java
  src/main/java/it/gov/pagopa/wispconverter/util/interceptor/ReInterceptor.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/wispconverter/CarrelloTest.java
  src/test/java/it/gov/pagopa/wispconverter/ConsumerTest.java
  src/test/java/it/gov/pagopa/wispconverter/HomeTest.java
  src/test/java/it/gov/pagopa/wispconverter/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/wispconverter/PaaInviaRTServiceTest.java
  src/test/java/it/gov/pagopa/wispconverter/ReceiptTest.java
  src/test/java/it/gov/pagopa/wispconverter/RptTest.java
  src/test/java/it/gov/pagopa/wispconverter/XmlUtilTest.java
  src/test/java/it/gov/pagopa/wispconverter/ZipUtilTest.java
Labels: patch, size/large
